"use client"; // Tambahkan ini di baris pertama

import { Geist, Geist_Mono } from "next/font/google";
import { useState } from "react";
import "./globals.css";

// Import font styles
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // State untuk mengatur mode expand/collapse
  const [isExpanded, setIsExpanded] = useState(false);

  // Fungsi toggle expand/collapse
  const toggleSidebar = () => {
    setIsExpanded((prev) => !prev);
  };

  return (
    <html lang="en">
      <head>
        {/* Metadata untuk halaman */}
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Sidebar */}
        <aside
          className={`fixed inset-y-0 left-0 z-10 ${
            isExpanded ? "w-56" : "w-16"
          } transition-all duration-300 flex flex-col border-r bg-white`}
        >
          <nav className="flex flex-col items-center py-6">
            {/* Tombol Toggle Sidebar */}
            <button
              onClick={toggleSidebar}
              className="flex h-10 w-10 items-center justify-center rounded-lg text-gray-600 hover:text-blue-600"
            >
              {/* Icon untuk toggle */}
              <svg
                xmlns="http://www.w3.org/2000/svg"
                className="h-6 w-6"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
                viewBox="0 0 24 24"
              >
                <path
                  d={
                    isExpanded
                      ? "M19 12H5M12 5l-7 7 7 7"
                      : "M4 6h16M4 12h16M4 18h16"
                  }
                />
              </svg>
            </button>

            {/* Sidebar Menu */}
            {[
              {
                href: "/",
                icon: (
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    className="h-6 w-6"
                    fill="none"
                    stroke="currentColor"
                    strokeWidth="2"
                    viewBox="0 0 24 24"
                  >
                    <path d="M13 2L3 14h7v8l10-12h-7V2z" />
                  </svg>
                ),
                srText: "PLN",
                label: "PLN",
              },
              {
                href: "pulsa",
                icon: (
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    className="h-6 w-6"
                    fill="none"
                    stroke="currentColor"
                    strokeWidth="2"
                    viewBox="0 0 24 24"
                  >
                    <path d="M7 2h10a2 2 0 0 1 2 2v18a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2zm5 18a1 1 0 1 0 0 2 1 1 0 0 0 0-2z" />
                  </svg>
                ),
                srText: "Pulsa",
                label: "Pulsa",
              },
              {
                href: "bpjs",
                icon: (
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    className="h-6 w-6"
                    fill="none"
                    stroke="currentColor"
                    strokeWidth="2"
                    viewBox="0 0 24 24"
                  >
                    <path d="M4 6h16a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2z" />
                    <path d="M4 10h16" />
                  </svg>
                ),
                srText: "BPJS",
                label: "BPJS",
              },
            ].map((item, idx) => (
              <div key={idx} className="relative group">
                <a
                  href={item.href}
                  className="flex items-center gap-4 px-4 text-gray-600 hover:text-blue-600"
                >
                  <div className="flex h-10 w-10 items-center justify-center rounded-lg">
                    {item.icon}
                  </div>
                  {/* Tampilkan label hanya jika sidebar dalam mode expanded */}
                  {isExpanded && (
                    <span className="text-sm font-medium">{item.label}</span>
                  )}
                </a>
                {/* Tooltip */}
                {!isExpanded && (
                  <div className="absolute left-14 top-1/2 -translate-y-1/2 hidden group-hover:block bg-gray-700 text-white text-xs font-medium rounded-lg px-2 py-1 shadow-lg">
                    {item.label}
                  </div>
                )}
              </div>
            ))}
          </nav>
        </aside>

        {/* Konten halaman */}
        <main className={`ml-${isExpanded ? "56" : "16"} transition-all`}>
          {children}
        </main>
      </body>
    </html>
  );
}
